### ISSUE TITLE
Code coverage job is failing

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/pystache#2]
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/badges*:refs/remotes/origin/badges* +refs/tags/badges*:refs/tags/badges*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 10 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/badges*:refs/remotes/origin/badges* +refs/tags/badges*:refs/tags/badges*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 17 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/badges*:refs/remotes/origin/badges* +refs/tags/badges*:refs/tags/badges*
  Error: The process '/usr/bin/git' failed with exit code 1
```

https://github.com/PennyDreadfulMTG/pystache/actions/runs/1378797536

**Comment by sarnold** [comment]
You just need to create/push the branch (but don't add any files to it).  The intent is for the badges branch to store the "base" coverage/badge, while the workflow should run on PR/push on whatever your default branches are, eg, `master` or both `master` and `develop`, etc. The if clause for updating the base coverage/badge itself should be restricted to `push` events in org repos (so the badge gets updated on PR merge).

Anyway, just [follow the usual steps](https://jiafulow.github.io/blog/2020/07/09/create-gh-pages-branch-in-existing-repo/) to create an orphan branch (but change the name to badges instead of gh-pages).

**Comment by bakert** [comment]
Orphan `badges` branch has been created and pushed. I'll leave this open until I see coverage work.

**Comment by bakert** [comment]
I ran the job manually and the coverage badge now shows "passing".
